In [15]:
import pandas as pd
df = pd.read_csv('earthquake_data.csv')

In [2]:
df.head()

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,01/02/1965,13:44:18,19.246,145.616,Earthquake,131.6,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,01/04/1965,11:29:49,1.863,127.352,Earthquake,80.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
2,01/05/1965,18:05:58,-20.579,-173.972,Earthquake,20.0,NaN,NaN,6.2,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic
3,01/08/1965,18:49:43,-59.076,-23.557,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic
4,01/09/1965,13:32:50,11.938,126.427,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23412 entries, 0 to 23411
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        23412 non-null  object
 1   Time                        23412 non-null  object
 2   Latitude                    23412 non-null  float64
 3   Longitude                   23412 non-null  float64
 4   Type                        23412 non-null  object
 5   Depth                       23412 non-null  float64
 6   Depth Error                 4461 non-null   float64
 7   Depth Seismic Stations      7097 non-null   float64
 8   Magnitude                   23412 non-null  float64
 9   Magnitude Type              23409 non-null  object
 10  Magnitude Error             327 non-null    float64
 11  Magnitude Seismic Stations  2564 non-null   float64
 12  Azimuthal Gap               7299 non-null   float64
 13  Horizontal Distance         1604 non-null   float64
 14  Horizontal Error            1156 non-null   float64
 15  Root Mean Square            17352 non-null  float64
 16  ID                          23412 non-null  object
 17  Source                      23412 non-null  object
 18  Location Source             23412 non-null  object
 19  Magnitude Source            23412 non-null  object
 20  Status                      23412 non-null  object
dtypes: float64(12), object(9)
memory usage: 3.8+ MB

In [4]:
df.describe()

,Latitude,Longitude,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Error,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square
count,23412.000000,23412.000000,23412.000000,4461.000000,7097.000000,23412.000000,327.000000,2564.000000,7299.000000,1604.000000,1156.000000,17352.000000
mean,1.679033,39.639961,70.767911,4.993115,275.364098,5.882531,0.071820,48.944618,44.163532,3.992660,7.662759,1.022784
std,30.113183,125.511959,122.651898,4.875184,162.141631,0.423066,0.051466,62.943106,32.141486,5.377262,10.430396,0.188545
min,-77.080000,-179.997000,-1.100000,0.000000,0.000000,5.500000,0.000000,0.000000,0.000000,0.004505,0.085000,0.000000
25%,-18.653000,-76.349750,14.522500,1.800000,146.000000,5.600000,0.046000,10.000000,24.100000,0.968750,5.300000,0.900000
50%,-3.568500,103.982000,33.000000,3.500000,255.000000,5.700000,0.059000,28.000000,36.000000,2.319500,6.700000,1.000000
75%,26.190750,145.026250,54.000000,6.300000,384.000000,6.000000,0.075500,66.000000,54.000000,4.724500,8.100000,1.130000
max,86.005000,179.998000,700.000000,91.295000,934.000000,9.100000,0.410000,821.000000,360.000000,37.874000,99.000000,3.440000

In [5]:
df.isnull().sum()

Date                              0
Time                              0
Latitude                          0
Longitude                         0
Type                              0
Depth                             0
Depth Error                   18951
Depth Seismic Stations        16315
Magnitude                         0
Magnitude Type                    3
Magnitude Error               23085
Magnitude Seismic Stations    20848
Azimuthal Gap                 16113
Horizontal Distance           21808
Horizontal Error              22256
Root Mean Square               6060
ID                                0
Source                            0
Location Source                   0
Magnitude Source                  0
Status                            0
dtype: int64

In [6]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [7]:
df = df.drop_duplicates()

In [8]:
#Handle missing values==> Filling median values in numeric columns
df = df.fillna(df.median(numeric_only=True))

In [9]:
print(df.info())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23412 entries, 0 to 23411
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        23412 non-null  object
 1   Time                        23412 non-null  object
 2   Latitude                    23412 non-null  float64
 3   Longitude                   23412 non-null  float64
 4   Type                        23412 non-null  object
 5   Depth                       23412 non-null  float64
 6   Depth Error                 23412 non-null  float64
 7   Depth Seismic Stations      23412 non-null  float64
 8   Magnitude                   23412 non-null  float64
 9   Magnitude Type              23409 non-null  object
 10  Magnitude Error             23412 non-null  float64
 11  Magnitude Seismic Stations  23412 non-null  float64
 12  Azimuthal Gap               23412 non-null  float64
 13  Horizontal Distance         23412 non-null  float64
 14  Horizontal Error            23412 non-null  float64
 15  Root Mean Square            23412 non-null  float64
 16  ID                          23412 non-null  object
 17  Source                      23412 non-null  object
 18  Location Source             23412 non-null  object
 19  Magnitude Source            23412 non-null  object
 20  Status                      23412 non-null  object
dtypes: float64(12), object(9)
memory usage: 3.8+ MB
None
Date                          0
Time                          0
Latitude                      0
Longitude                     0
Type                          0
Depth                         0
Depth Error                   0
Depth Seismic Stations        0
Magnitude                     0
Magnitude Type                3
Magnitude Error               0
Magnitude Seismic Stations    0
Azimuthal Gap                 0
Horizontal Distance           0
Horizontal Error              0
Root Mean Square              0
ID                            0
Source                        0
Location Source               0
Magnitude Source              0
Status                        0
dtype: int64

In [10]:
# Filling missing sensor/statistical measurement columns with median
for col in [
    "Depth Error", "Depth Seismic Stations", "Magnitude Error", "Magnitude Seismic Stations",
    "Azimuthal Gap", "Horizontal Distance", "Horizontal Error", "Root Mean Square"
]:
    df[col] = df[col].fillna(df[col].median())

# Fill categorical with mode if there are very few missing
for col in ["Magnitude Type"]:
    df[col] = df[col].fillna(df[col].mode().iloc[0])

# checking the null/missing values again
print(df.isnull().sum()) #all values should be zeros

# Save cleaned data
df.to_csv('earthquake_data_clean.csv', index=False)

Date                          0
Time                          0
Latitude                      0
Longitude                     0
Type                          0
Depth                         0
Depth Error                   0
Depth Seismic Stations        0
Magnitude                     0
Magnitude Type                0
Magnitude Error               0
Magnitude Seismic Stations    0
Azimuthal Gap                 0
Horizontal Distance           0
Horizontal Error              0
Root Mean Square              0
ID                            0
Source                        0
Location Source               0
Magnitude Source              0
Status                        0
dtype: int64

In [11]:
#Week 2
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

In [12]:
df = pd.read_csv('earthquake_data_clean.csv') #loading cleaned dataset

In [13]:
# Convert ISO 8601 datetime string to pandas datetime
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
print(df[df['Date'].isnull()])

      Date                      Time  Latitude  Longitude        Type  Depth  \
3378   NaT  1975-02-23T02:58:41.000Z     8.017    124.075  Earthquake  623.0
7512   NaT  1985-04-28T02:53:41.530Z   -32.998    -71.766  Earthquake   33.0
20650  NaT  2011-03-13T02:23:34.520Z    36.344    142.344  Earthquake   10.1

       Depth Error  Depth Seismic Stations  Magnitude Magnitude Type  ...  \
3378           3.5                   255.0        5.6             MB  ...
7512           3.5                   255.0        5.6             MW  ...
20650         13.9                   289.0        5.8            MWC  ...

       Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
3378                         28.0           36.0               2.3195
7512                         28.0           36.0               2.3195
20650                        28.0           32.3               2.3195

       Horizontal Error  Root Mean Square          ID Source Location Source  \
3378                6.7              1.00  USP0000A09     US              US
7512                6.7              1.30  USP0002E81     US              US
20650               6.7              1.06  USP000HWQP     US              US

      Magnitude Source    Status
3378                US  Reviewed
7512               HRV  Reviewed
20650             GCMT  Reviewed

[3 rows x 21 columns]

In [16]:
# Convert 'Time' column with utc=True to handle mixed time zones
df['Datetime'] = pd.to_datetime(df['Time'], utc=True, errors='coerce')

# Convert to naive local time if desired (optional)
df['Datetime'] = df['Datetime'].dt.tz_convert(None)

# Now extract datetime features safely
df['Year'] = df['Datetime'].dt.year
df['Month'] = df['Datetime'].dt.month
df['Day'] = df['Datetime'].dt.day
df['Hour'] = df['Datetime'].dt.hour
df['Minute'] = df['Datetime'].dt.minute

# Drop old columns to avoid confusion
df = df.drop(['Date', 'Time'], axis=1)

/tmp/ipython-input-3393871181.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Datetime'] = pd.to_datetime(df['Time'], utc=True, errors='coerce')

In [17]:
from sklearn.preprocessing import LabelEncoder

categorical_cols = ['Type', 'Magnitude Type', 'Source', 'Location Source', 'Magnitude Source', 'Status']
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))

In [18]:
from sklearn.preprocessing import StandardScaler

numeric_cols = ['Latitude', 'Longitude', 'Depth', 'Depth Error', 'Depth Seismic Stations',
                'Magnitude', 'Magnitude Error', 'Magnitude Seismic Stations',
                'Azimuthal Gap', 'Horizontal Distance', 'Horizontal Error', 'Root Mean Square']
scaler = StandardScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

In [19]:
from sklearn.model_selection import train_test_split

X = df.drop('Magnitude', axis=1)  # Or your specified target
y = df['Magnitude']  # Or your custom target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)